language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - iojs
script: make lint test
cache:
  directories:
    - node_modules
sudo: false
env:
  global:
    secure: ZRRIvFc4yGEFUXj/6uu/0aLzKbk4qnkj2yLXBBkGANjT0eAlXgCOsbNVSswXX333NyXqUVOWl6dP1bL/veBN9o0Nou3CYwpbOz/LTFfdvifPA/80M5HhnkxWxQAjxiB4LNmqKDeIqZtHtAwxi0wlSKUwY4WNUy95uT+jyQbLZjk=
